# Generated by Django 5.2.11 on 2026-04-08 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_feedback_table_feedback_tips_table_tip_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tips_table',
            name='tip_id',
        ),
    ]
