# Generated by Django 5.2.11 on 2026-05-02 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_tips_table_tip_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_table',
            old_name='generated_code',
            new_name='output_file',
        ),
        migrations.RemoveField(
            model_name='image_table',
            name='output_format',
        ),
    ]
