# Generated by Django 5.2.11 on 2026-05-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_generated_code_image_table_output_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text_table',
            name='generated_code',
            field=models.CharField(max_length=5000),
        ),
    ]
