from django.urls import path

from myapp import views

urlpatterns = [
    path('login',views.loginn),
    path('logout_get',views.logout_get),
    path('forgot_get',views.forgot_get),
    path('forgotPassword_otp',views.forgotPassword_otp),
    path('verifyOtp',views.verifyOtp),
    path('verifyOtpPost',views.verifyOtpPost),
    path('new_password',views.new_password),
    path('changePassword',views.changePassword),
    path('user_signup_post',views.user_signup_post),
    path('admin_home',views.admin_home),
    path('admin_change_p',views.admin_change_p),
    path('admin_change_p_post',views.admin_change_p_post),
    path('admin_fb',views.admin_fb),
    path('admin_reply_post',views.admin_reply_post),
    path('admin_reply/<id>',views.admin_reply),
    path('admin_tips',views.admin_tips),
    path('admin_tips_post',views.admin_tips_post),
    path('delete_tip/<int:id>', views.delete_tip),
    path('admin_view_com',views.admin_view_com),
    path('admin_view_user',views.admin_view_user),
    path('delete_user/<id>',views.delete_user),
    path('user_home',views.user_home),
    path('user_change_p',views.user_change_p),
    path('user_change_p_post',views.user_change_p_post),
    path('user_complaint',views.user_complaint),
    path('user_fb',views.user_fb),
    path('user_fb_post',views.user_fb_post),
    path('user_img_his',views.user_img_his),
    path('user_img_to_code',views.user_img_to_code),
    path('user_img_to_code_post',views.user_img_to_code_post),
    path('user_text_to_code',views.user_text_to_code),
    path('user_textcode_his',views.user_textcode_his),
    path('user_send_comp',views.user_send_comp),
    path('user_send_comp_post',views.user_send_comp_post),
    path('user_signup',views.user_signup),
    path('user_view_prof',views.user_view_prof),
    path('user_view_tips',views.user_view_tips),
    path('user_prof_edit',views.user_prof_edit),
    path('user_prof_edit_post',views.user_prof_edit_post),
    path('user_gen_code',views.user_gen_code),
    path('user_text_to_code_post',views.user_text_to_code_post),

]
